name: Test System

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile code
        run: mkdir build && cd build && cmake .. && make

      - name: Test Frame Operations
        run: ./build/test_frame_ops

      - name: Test Big-Endian Frame Operations
        run: ./build/test_frame_ops_be
  
  create-release:
    needs: test
    if: startsWith(github.ref_name, 'v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          prerelease: true
          generateReleaseNotes: true