name: Test System

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile code
        run: make test_frame_ops

      - name: Test Frame Operations
        run: ./bin/test_frame_ops
